name: Sync Langflow Flows

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Sync Langflow flows
        run: python -m langflow-config.sync_langflow.sync_langflow
        env:
          LANGFLOW_URL: ${{ secrets.LANGFLOW_URL }}
          LANGFLOW_API_TOKEN: ${{ secrets.LANGFLOW_API_TOKEN }}
          BEFORE_COMMIT: ${{ github.event.before }}
          AFTER_COMMIT: ${{ github.sha }}
