name: Sync Langflow Flows

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          rm /home/ubuntu/langflow-config-runner/_work/_tool/Python/3.10.17/x64/bin/pip
          curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
          python get-pip.py
          python -m pip install --upgrade pip
          pip install requests

      - name: Sync Langflow flows
        run: python -m langflow-config.sync_langflow.main --langflow-url http://localhost:7860 --enable-openwebui --openwebui-url http://localhost:3000 --openwebui-api-key eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImYzMGNiNmYyLWJhMzYtNGM5Ni1hZGU0LWZiNzUzMjdiOGI2ZCJ9._CbGV9JZFJ8HDru829YVBarGp8C5eFkP37OTn8-wMo0
        env:
          LANGFLOW_URL: ${{ secrets.LANGFLOW_URL }}
          LANGFLOW_API_TOKEN: ${{ secrets.LANGFLOW_API_TOKEN }}
          BEFORE_COMMIT: ${{ github.event.before }}
          AFTER_COMMIT: ${{ github.sha }}
